### ISSUE TITLE
Download external schemas from git

### ISSUE THREAD

**Issue by adzialocha** [p2panda/fishy#1]
```toml
# Example
[test.fields]
some_field = { type = "str", schema = { id = "some_schema_0020...", git = "https://..." } }
```
