### ISSUE TITLE
Get external schemas from different folders

### ISSUE THREAD

**Issue by adzialocha** [p2panda/fishy#2]
```toml
# Example
[test.fields]
some_field = { type = "str", schema = { id = "some_schema_0020...", path = "../some_schema" } }
```
